# currently does not work
scroll_offset = 6

xdg_open = false
# use_trash = true

[display]
# ratios for parent view, current view and preview
collapse_preview = true
column_ratio = [2, 3, 4]
show_borders = true
show_hidden = false
show_icons = true
show_preview = true
tilde_in_titlebar = true

[display.sort]
# lexical, mtime, natural
method = "natural"
case_sensitive = false
directories_first = true
reverse = false

[preview]
#max_preview_size = 3145728 # 3MB
preview_images = false
# preview_script = "/home/kenny/.config/joshuto/preview.sh"
# testeando lo de abajo
# preview_shown_hook_script = "/home/kenny/.config/joshuto/on_preview_shown.sh"
# preview_removed_hook_script = "/home/kenny/.config/joshuto/on_preview_removed.sh"

[tab]
# inherit, home, root
home_page = "inherit"
